server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
     defaultZone: http://localhost:10087/eureka  #注册中心项目的地址
  server:
    enable-self-preservation: false # 关闭了自我保护
